name: CI

on:
  push:
    branches:
      - master
      - 'feature/*'
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.13.1'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$(pwd)/TAP-MinecraftFrameworkAPI" >> $GITHUB_ENV

    - name: Run tests and generate coverage report
      run: |
        pytest --cov=TAP-MinecraftFrameworkAPI/Framework --cov-report=xml TAP-MinecraftFrameworkAPI/Framework/_tests

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

ignore:
  - "TAP-MinecraftFrameworkAPI/Framework/Agents"

